package project;

import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import java.awt.Dimension;


public class FrameStart extends javax.swing.JFrame {
	
    // Khai báo biến                     
    private JButton buttonAbout;
    private JButton buttonDecode;
    private JButton buttonEncode;
    private JButton buttontExit;
    private JLabel labelImage;
    private JLabel labelTitle;	

    /**
     * Creates new form FrameStart
     */
    public FrameStart() {
    	setTitle("HUFFMAN");
    	setResizable(false);
    	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
                       
    private void initComponents() {
  
 /* 
  	Tạo các button chứa các chức năng của ứng dụng và xử lý sự kiện cho chúng
 */
    	
    	
        buttonEncode = new JButton(); // button Encode, gọi ra giao diện mới để thực hiện chức năng mã hóa chuỗi kí tự thành dãy bit 0 1
        buttonEncode.setText("ENCODE");
        getContentPane().add(buttonEncode);
        buttonEncode.setBounds(210, 120, 90, 22);
        buttonEncode.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		FrameEncode frameEncode = new FrameEncode();
        		frameEncode.setVisible(true);
        	
        	}
        });
        
        buttonDecode = new JButton(); // button Decode, gọi ra giao diện mới để thực hiện chức năng giải mã chuỗi bit 0 1 thành chuỗi kí tự đã mã hóa
        buttonDecode.setText("DECODE");
        getContentPane().add(buttonDecode);
        buttonDecode.setBounds(210, 190, 90, 22);
        buttonDecode.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		FrameDecode frameDecode = new FrameDecode();
        		frameDecode.setVisible(true);
        	}
        	
        });
        
        buttonAbout = new JButton(); // button About, chứa thông tin về ứng dụng cũng như thông tin người tạo ra ứng dụng
        buttonAbout.setText("ABOUT US");
        getContentPane().add(buttonAbout);
        buttonAbout.setBounds(210, 260, 90, 22);
        buttonAbout.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		FrameAbout frameAbout = new FrameAbout();
        		frameAbout.setVisible(true);
        	}
        });
        
        buttontExit = new JButton(); // button Exit, có chức năng thoát khỏi ứng dụng
        buttontExit.setText("EXIT");
        buttontExit.setBounds(210, 334, 90, 22);
        getContentPane().add(buttontExit);
        buttontExit.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		setVisible(false);
        	}
        });
        

        labelTitle = new javax.swing.JLabel(); // label chứa Title của ứng dụng
        labelTitle.setFont(new java.awt.Font("Segoe UI", 0, 18));
        labelTitle.setForeground(new java.awt.Color(204, 204, 255));
        labelTitle.setText("HUFFMAN ENCODING");
        getContentPane().add(labelTitle);
        labelTitle.setBounds(160, 70, 210, 25);
        
        labelImage = new javax.swing.JLabel(); // label chứa hình ảnh Background của ứng dụng
        labelImage.setHorizontalAlignment(SwingConstants.CENTER);
        setMinimumSize(new Dimension(500, 480));
        getContentPane().setLayout(null);
        labelImage.setIcon(new javax.swing.ImageIcon("D:\\Study\\Nam2\\HocKy2\\DALTUD\\background.jpg")); // NOI18N
        labelImage.setMinimumSize(new java.awt.Dimension(500, 500));
        labelImage.setPreferredSize(new java.awt.Dimension(500, 50));
        getContentPane().add(labelImage);
        labelImage.setBounds(-12, 0, 542, 445);
        
        setLocationRelativeTo(null); // Hiển thị cửa sổ ứng dụng lên chính giữa màn hình
    }                       


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameStart().setVisible(true);
            }
        });
    }
   
}
